#!/bin/bash
#Licensed under the GPL
#Authors: Alex Stone and Christopher Cherrett
#OOStudio-v2 2009/08/25
#Modified 2011/02/03

usage() {
	echo -e "OOStudio Script for starting your Open Octave Studio\n"
	echo -e "\t./OOStudio (optional -d to start up in debug mode)"
}

if [[ "$1" = "-h" ]]; then
	usage
	exit 0
fi

debug_output="false"

function killprocesses()
{
	echo "killing processes ......"
	
	if [[ "$debug_output" == "false" ]]; then
		killall jconvolver >/dev/null 2>&1
		sleep 2
		killall linuxsampler >/dev/null 2>&1
		sleep 2
		killall jackd >/dev/null 2>&1
		sleep 2
	else
		killall jconvolver
		sleep 2
		killall linuxsampler
		sleep 2
		killall jackd
		sleep 2
	fi
}

while getopts ":d" opts
do
	case $opts in
		d)
		debug_output="true";
		;;
	esac
done

trap ctrl_c INT


function ctrl_c()
{
	killprocesses
	exit
}
function start_jack()
{
	echo "starting jackd..."
	if [[ $debug_output -eq "false" ]]; then
		/usr/bin/jackd -p2048 -t2000 -dfirewire -p512  >/dev/null 2>&1 &
	else
		/usr/bin/jackd -p2048 -t2000 -dfirewire -p512 &
	fi
	sleep 2
}
function start_linuxsampler()
{
	echo "starting linuxsampler..."
	if [[ "$debug_output" == "false" ]]; then
		/usr/local/bin/linuxsampler >/dev/null 2>&1 &
	else
		/usr/local/bin/linuxsampler &
	fi
	sleep 5
	echo "sending lscp commands to linuxsampler..."
	if [[ "$debug_output" == "false" ]]; then
		cat  /home/derick/linuxaudio/openoctave2/template_oom/jazzbandsetup_LS_all1.lscp | nc localhost 8888 & >/dev/null 2>&1 &
	else
		cat  /home/derick/linuxaudio/openoctave2/template_oom/jazzbandsetup_LS_all1.lscp | nc localhost 8888 &
	fi
	sleep 30
}
function start_oomidi()
{	
	oomidi_running=`ps ax | grep "[o]midi"`
	if [[ -z $oomidi_running ]]; then
		echo "starting oomidi..."
		if [[ "$debug_output" == "false" ]]; then
			oomidi >/dev/null 2>&1 &
		else
			oomidi &
		fi
		sleep 8
	fi
}
function start_jconvolver()
{
	echo "starting jconvolver..."
	if [[ "$debug_output" == "false" ]]; then
		/usr/bin/jconvolver /home/derick/linuxaudio/openoctave2/template_oom/ambconster_d.conf >/dev/null 2>&1 &
	else
		/usr/bin/jconvolver /home/derick/linuxaudio/openoctave2/template_oom/ambconster_d.conf &
	fi
	sleep 4
}
function start_ardour()
{
        echo "starting ardour..."
	if [[ "$debug_output" == "false" ]]; then
		/usr/bin/ardour2 /home/derick/linuxaudio/openoctave_backup/openoctave_ardour_2/oomidi_template1.ardour >/dev/null 2>&1 &
	else
		/usr/bin/ardour2 /home/derick/linuxaudio/openoctave_backup/openoctave_ardour_2/oomidi_template1.ardour &
	fi
	sleep 2
}
function startup()
{
	killprocesses
	return
}

startup

echo "Starting Open Octave Studio ......"

start_jack
start_linuxsampler
start_jconvolver
start_oomidi

echo "To stop the Open Octave Studio press CTRL + C"

for (( ; ; ))
do
	sleep 10
	jack_running=`ps ax | grep "[j]ackd"`
	ls_running=`ps ax | grep "[l]inuxsampler"`
	jc_running=`ps ax | grep "[j]conv"`

	if [[ -z $jack_running ]]; then
		killprocesses
		start_jack
		start_linuxsampler	
		start_jconvolver
		killall -HUP oomidi
	elif [[ -z $ls_running ]]; then
		start_linuxsampler	
		start_jconvolver
		killall -HUP oomidi
	elif [[ -z $jc_running ]]; then
		start_jconvolver
		killall -HUP oomidi
	fi

done
